### ISSUE TITLE
【朙月拼音·简化字】 方案下简繁切换无效

### ISSUE THREAD

**Issue by LenKiMo** [rime/rime-pinyin-simp#5]
小狼毫 0.11.1，使用【朙月拼音·简化字】方案。

在 `default.custom.yaml` 下写入快捷键设置：
```
  key_binder:
    bindings:
     - {accept: "Control+Shift+F", toggle: simplification, when: always}
```

保存并重新部署后，敲击快捷键，可以看见输入法提示信息`漢字`。但是上屏词汇仍是简体字，且候选中全无相应繁体字形。

不知这是刻意为之——即简体字方案下将强制使用简体字形，还是该切换功能尚未实现？

**Comment by Riamuu** [comment]
一样的问题，请问解决了吗

**Comment by LEOYoon-Tsaw** [comment]
得把opencc換成簡轉繁吧

**Comment by lotem** [comment]
这个输入方案没有配置简繁转换的功能。
